# github action to publish cardealer app to azure

name: Build .NET App and publish it to azure -- Car Dealer

on:
  push:

env:
  AZURE_WEBAPP_NAME: "app-cardealer-eastus-dev-001"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # # Install dependencies
      # - name: Install dependencies
      #   run: dotnet restore

      # Build
      - name: Build
        run: dotnet build --configuration Release

      # Publish
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # Deploy
      - name: Deploy to azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ./publish
